<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="styles/healthrecords.css">
    </head>
    <body>
        <div class="table">
            <table>
                <thead>
                    <tr>
                        <th id="patient">Patient ID</th>
                        <th id="date">Date of Visit</th>
                        <th id="time">Time of Visit</th>
                        <th id="height">Height (in cm)</th>
                        <th id="weight">Weight (in Kg)</th>
                        <th id="bmi">BMI</th>
                        <th id="bloodp">Blood pressure (in mmHg)</th>
                        <th id="sugarl">Sugar Level (in g/mol)</th>
                        <th id="reason">Reason for visit</th>
                    </tr>
                </thead> 
                <tbody>          
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                <tr>
                    <td>a</td>
                    <td>a</td>
                    <td>a</td>
                    <td>b</td>
                    <td>b</td>
                    <td>c</td>
                    <td>b</td>
                    <td>a</td>
                    <td>a</td>
                </tr>
                
                </tbody>
            </table>
        </div>
    </body>
</html>